algoritmo "Exercício 1"
// Função :Faça um algoritmo que receba dois números e exiba o resultado da sua soma. 
// Autor :Asheley
// Data : 23/09/2025
// Seção de Declarações 
var
n1, n2: inteiro
inicio
escreval("Digite primeiro número")
leia(n1)
escreval("Digite o segundo número")
leia(n2)
escreval("A soma é:", n1 + n2)
fimalgoritmo
//Esse algoritmo soma dois números escolhido pelo usuário
