algoritmo "semnome"
// Função :Faça um algoritmo que receba um número e mostre uma mensagem caso este número seja maior que 10.
// Autor :
// Data : 16/10/2025
// Seção de Declarações 
var
numero: Real
inicio
escreva ("Digite numero:")
leia (numero)

se numero> 10 entao
   escreva("O número é maior que 10")
fimse
fimalgoritmo
//Esse algoritmo verifica se um número é maior que 10 e exibe uma mensagem se for verdadeiro.
