algoritmo "ex2"
// Função :
// Autor : ashe
// Data : 23/09/2025
// Seção de Declarações 
var
n1, n2: inteiro
inicio
escreval("Digite o primeiro número:")
leia(n1)
escreval("Digite o segundo número:")
leia(n2)
escreval("A soma é:", n1 + n2)
escreval("A subtração é:" , n1 - n2)
escreval("A multiplicação é:", n1 * n2)
escreval("A divisão é:", n1 / n2)
escreval("O resto é:", n1 MOD n2)
fimalgoritmo
