algoritmo "semnome"
// Função :
// Autor :
// Data : 13/10/2025
// Seção de Declarações
var
n: inteiro
inicio
escreval("Digite o número: ")
leia(n)
se (n > 80) entao
   escreval("Este número é maior que 80")
senao
   se (n < 25) entao
      escreval("Este número é menor que 25")
   senao
      se (n = 40) entao
         escreval("Este número é igual a 40")
      fimse
   fimse
fimse
fimalgoritmo
