algoritmo "semnome"
// Função :
// Autor :
// Data : 13/10/2025
// Seção de Declarações
var
n1, n2: inteiro
inicio
escreval("Digite o número: ")
leia(n1)
escreval("Digite o número: ")
leia(n2)
se n1 = n2 entao
   escreval("Os número são iguais")
senao
   escreval("Os números são diferentes")
   se n1 > n2 entao
      escreval("O número maior é: ", n1)
   senao
      escreval("O número maior é: ", n2)
   fimse
fimse
fimalgoritmo
