algoritmo "ex6"
// Função :
// Autor : ashe
// Data : 25/09/2025
// Seção de Declarações 
var
A, B, TEMP: inteiro
inicio
escreval("Digite o valor de A:")
leia(A)
escreval("Digite o valor de B:")
leia(B)
escreval("O valor de A é:", A)
escreval("O valor de B é:", B)
escreval("Efetuando a troca")
TEMP <- A
A <- B
B <- TEMP
escreval("O valor de A é:", A)
escreval("O valor de B é:", B)
fimalgoritmo
